### ISSUE TITLE
Confused environment

### ISSUE THREAD

**Issue by al3xandru** [yyuu/pyenv-virtualenv#172]
This is more of a question, rather that an issue, but I have no idea what led to it.

1. Who sets `PYENV_VERSION` and based on what information?

```
> pyenv versions
  system
* 2.7.10 (set by PYENV_VERSION environment variable)
  2.7.11
  2.7.11/envs/2.7.11-ccm
  2.7.11/envs/2.7.11-datastax-python
  2.7.11-ccm
  2.7.11-datastax-python
```

2. At the same time:

```
> pyenv global
2.7.11
```

3. And in the current directory:

```
> pyenv local
2.7.11-datastax-python
> pyenv which python
/Users/alex/.pyenv/versions/2.7.10/bin/python
```

This last one doesn't look good to me.

**Comment by yyuu** [comment]
`PYENV_VERSION` is an environment variable used by `pyenv` and it is most favorably chosen by pyenv. Either `pyenv shell`, `pyenv activate ${venv}` or some other user's shell command (e.g. `export PYENV_VERSION=foo`) will set the variable.

https://github.com/yyuu/pyenv#choosing-the-python-version

The last output isn't weird since you're setting `PYENV_VERSION` as `2.7.10`.  The `pyenv version` (or `pyenv versions`) should show you currently activated python version(s) and its source. If you want to let your pyenv to choose the _local_ version in the directory, you need to run `pyenv shell --unset` (or, `unset PYENV_VERSION`) first.

**Comment by al3xandru** [comment]
Thanks @yyuu for the follow up.

1. When is the `PYENV_VERSION` env variable set?
2. Shouldn't it be unset when entering a directory which has a `.python-version` file?

**Comment by blueyed** [comment]
> When is the PYENV_VERSION env variable set?

Manually, or with `pyenv shell …`.

> Shouldn't it be unset when entering a directory which has a .python-version file?

Then it would not get preferred over `.python-version` (from `pyenv local`)..

**Comment by blueyed** [comment]
@al3xandru 
You can `export PYENV_DEBUG=1`, e.g. in a shell or your shell startup file to see what pyenv does, e.g. if it activates some virtualenv etc.
Then search in that output for `PYENV_VERSION`.

**Comment by yyuu** [comment]
No updates.
