### ISSUE TITLE
conda package activate/deactivate scripts are not run

### ISSUE THREAD

**Issue by cpaulik** [yyuu/pyenv-virtualenv#173]
It seems that conda package activate scripts are not run when using pyenv.

Conda supports activate and deactivate scripts for packages. For example [GDAL uses it to set environment variables](https://github.com/conda/conda-recipes/blob/master/gdal/posix/activate.sh).

These scripts are stored in e.g. `~/.pyenv/versions/miniconda-3.16.0/envs/gdal_test/etc/conda/activate.d/` and I think they are called in the original anaconda activate script [here](https://github.com/conda/conda-env/blob/v2.4.5/bin/activate#L82-L83)

But when I activate an environment managed by pyenv the `GDAL_DATA` environment variable is not set whereas a standalone conda environment performs correctly.

**Comment by yyuu** [comment]
The package scripts won't work since it's not implemented in pyenv-virtualenv for now. I guess that we can add the feature by inserting few lines around https://github.com/yyuu/pyenv-virtualenv/blob/98bb240843ab76ece54dbf9c8e1a598859c43ba3/bin/pyenv-sh-activate#L180-L194

I think this feature is worth to be implemented in pyenv-virtualenv. I'll try to prepare some patch if I get a chance.

**Comment by yyuu** [comment]
@cpaulik I've pushed #174. Please give it a try.

**Comment by cpaulik** [comment]
Thank you. This works exactly as it should.
