### ISSUE TITLE
pyenv-virtualenv slows down zsh considerably

### ISSUE THREAD

**Issue by marshallpierce** [yyuu/pyenv-virtualenv#42]
If `eval "$(pyenv virtualenv-init -)"` is in my zshenv, every time a command finishes there is a delay of about a second. Even hitting the enter key to cause another prompt without entering a command is slow.

Judging by what init does to the shell, perhaps this is because this command is slow:
pyenv activate --no-error --verbose

I do not have PYENV_ACTIVATE set, so that branch of the init logic would be hit.

**Comment by blueyed** [comment]
@wakenmeng 
> Is it necessary to run eval "$(pyenv virtualenv-init -)" everytime I press enter?

That should not be the case..
Please try using `export PYENV_DEBUG=1` to see what is going on.

@marshallpierce 
Can you check if running `pyenv activate --no-error --verbose` manually is slow as well?
Apart from that, using `export PYENV_DEBUG=1` might help you debugging this, too.

**Comment by blueyed** [comment]
@marshallpierce @wakenmeng 
Can you provide feedback, please?

**Comment by wakenmeng** [comment]
appologize for being late, I omit the configuration `eval "$(pyenv virtualenv-init -)"` and it works for me.

**Comment by yyuu** [comment]
The performance tuning of shell script is hell :disappointed: 

If the speed is important for your installation, users of pyenv-virtualenv have an option to skip setting up `eval "$(pyenv virtualenv-init -)"` in his/her shell configuration. Since it's just for doing activate/deactivate of virtualenv based on current pyenv versions, user of pyenv-virtualenv still can switch virtualenvs as same manor as vanilla pyenv does. It would not cause problem any serious problems on most cases. I believe it'd be sufficient as a solution for this.

**Comment by blueyed** [comment]
@wakenmeng 
I see - it's not running the "init", but it's the code setup to autoactivate your virtualenv.

I am not using this myself (because of the performance implications).
I recommend using something like https://github.com/Tarrasch/zsh-autoenv, which allows you to trigger scripts when entering/leaving some directory.  From there you can then call `pyenv activate` or `pyenv deactivate` (on the "leave" event).
