### ISSUE TITLE
Feature suggestion: clone virtualenv to new env

### ISSUE THREAD

**Issue by al3xandru** [yyuu/pyenv-virtualenv#6]
While working on different library version it would be extremely helpful to be able to clone an existing virtualenv.

Right now what I do is:
1.  `pip freeze > requirements.txt` in the current virtualenv
2. `pyenv virtualenv ...`
3. `pyenv shell newvirtualenv`
4. `pip install -r requirements.txt`

Not too bad, but it could be easier.

**Comment by neverfox** [comment]
That's a cool plugin and all, but it doesn't seem to support virtualenvs that you want to move from one parent to another. For example, say I have `3.6.4` installed and a virtualenv installed under it (`/usr/local/Cellar/pyenv/1.2.3/versions/3.6.4/envs/my-venv`). Now I install `3.6.5` and because I want `my-env` to use that instead, I want it to be at `/usr/local/Cellar/pyenv/1.2.3/versions/3.6.5/envs/my-venv`. Is there a process for making that happen without the manual steps @al3xandru mentioned?
