### ISSUE TITLE
pyenv virtualenv not matching ucs4 installation

### ISSUE THREAD

**Issue by macklin** [yyuu/pyenv-virtualenv#67]
I'm trying to install a virtual environment that uses UCS-4 encoding.  I've installed my base python installation with:

```bash
PYTHON_CONFIGURE_OPTS="--enable-unicode=ucs4" pyenv install 2.7.5
mv $PYENV_ROOT/versions/2.7.5 $PYENV_ROOT/versions/2.7.5_ucs4
pyenv install 2.7.5
pyenv global 2.7.5_ucs4
```

If I run `python -c "import sys; print sys.maxunicode"`, it prints `1114111`, indicating that UCS-4 is installed.  When I then run:

```bash
pyenv virtualenv vEnv
pyenv local vEnv
python -c "import sys; print sys.maxunicode"
```

it prints out `65535`, indicating UCS-2 is installed.

Should I be doing something differently?

**Comment by macklin** [comment]
Upon further investigation, it looks like `pyenv virtualenv` links back to my version `2.7.5` which is UCS-2 rather than my `2.7.5_ucs4`.  Obviously by manually moving around base python installations (`mv`'ing `2.7.5` to `2.7.5_ucs4` above) I violated some assumptions that were made by pyenv.

Is there a recommended way to manage these kinds of different python installations (that had different compile options) for the same python version?

**Comment by blueyed** [comment]
> pyenv install 2.7.5 --name 2.7.5_ucs4

That seems useful.

@yyuu 
Would that be a valid feature request for pyenv?

**Comment by yyuu** [comment]
pyenv-alias might be sufficient for such usecase.

https://github.com/s1341/pyenv-alias

**Comment by yyuu** [comment]
@macklin Because the python's modules are configured to load files from the path configured as `--prefix` in `./configure`, basically I'd NOT recommend you to rename the installed version directory manually. As I wrote in my previous comment, there's a plugin of `pyenv-alias` and it'll help you to setting up `--prefix` with custom name during the installation. Please try using it if you'd like to use custom version name.
